# docker-compose.yml
version: '3'
 
services:
  traefik:
    image: traefik:v2.3
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
      - ./traefik.yml:/etc/traefik/traefik.yml
    networks:
      - proxy-network
    labels:
       - "traefik.enable=true"
       - "traefik.docker.network=proxy-network"
       - "traefik.http.routers.traefik.entrypoints=web"
       - "traefik.http.routers.traefik.rule=Host(`traefik.zero`)"
       - "traefik.http.routers.traefik.service=api@internal"
       - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"

       - "traefik.http.routers.traefik-secure.rule=Host(`traefik.zero`)"
       - "traefik.http.routers.traefik-secure.entrypoints=websecure"
       - "traefik.http.routers.traefik-secure.service=api@internal"
       - "traefik.http.routers.traefik-secure.tls=true"
       - "traefik.http.routers.traefik-secure.tls.certresolver=myresolver"
       - "traefik.http.routers.traefik-secure.middlewares=fausto_redirect"

# Redirect Scheme HTTP -> HTTPS
       - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
       - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.permanent=true"

# redirect middleware (simple)
       - "traefik.http.middlewares.fausto_redirect.redirectregex.regex=traefik.zero/fausto(.)*"
       - "traefik.http.middlewares.fausto_redirect.redirectregex.replacement=fausto.net.ar"
       - "traefik.http.middlewares.fausto_redirect.redirectregex.permanent=true"

 
networks:
  proxy-network:
    external: true
